version: '3.7'

services:
  portfolio:
    image: ${DOCKER_REGISTRY-}portfolio
    container_name: portfolio
    build:
      context: .
      dockerfile: Portfolio/Dockerfile
    networks: 
      - portfolio-net
    restart: always
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - ./portfolio.pfx:/https/portfolio.pfx
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=!BassCase987
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/portfolio.pfx

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DB: portfolioDB
      MYSQL_ROOT_PASSWORD: "!BassCase987"
      MYSQL_PASSWORD: "!BassCase987"
      MYSQL_USER: devin
    volumes:
      - ./docker/:/docker-entrypoint-initdb.d/
    networks:
      - portfolio-net
    ports:
      - 5000:3306

networks:
  portfolio-net:
    driver: 
      bridge
